### ISSUE TITLE
L1/L2 regularization and Wine Quality Data Set

### ISSUE THREAD

**Issue by leopeng1995** [dtnewman/gradient_descent#5]
I am working on add some contents about L1/L2 regularizaiton.

In addition, I wanna add the [Wine Quality Data Set](https://archive.ics.uci.edu/ml/datasets/Wine+Quality) from UCI Machine Learning Repository.

Can you make me a collaborator? @dtnewman

**Comment by leopeng1995** [comment]
And also, do you have a plan of writing a series wiki book like [tinyrender](https://github.com/ssloy/tinyrenderer/wiki)? I think proposing more interesting and funny examples will make the tutorial more popular.

**Comment by leopeng1995** [comment]
For now, I realized a[ Logistic Classifier](https://github.com/leopeng1995/machine_learning/blob/master/02%20logistic%20regression/logistic_regression.ipynb) based on Particle Swarm Optimization (I am also working on changing this to SGD and mnist data set). And something like ROC curve added.

**Comment by dtnewman** [comment]
Alright... some answers to your questions here:
- Happy to make you a collaborator. I just did this. Looking forward to seeing what you add!
- I originally wrote this notebook up when I was giving a lecture on this in graduate school. Honestly, it's been a while since then and I don't really have plans to extend this much further for the time being. But it's great if you have ideas to make it better!
